# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('life', 'life'), ('tech', 'tech')], max_length=5, null=True),
        ),
    ]
