# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createtime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='favs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
