# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20171123_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
